name: Fetch template

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  fetch_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4

      - name: Fetch
        run: |
          git config --global user.email "719887163@qq.com"
          git config --global user.name "xia0hj"
          git remote add template_repo https://github.com/xia0hj/my-vscode-extension-template.git
          git fetch template_repo main:template_sync
      
      - name: Push
        run: git push origin template_sync

